site_name: pytest-cookies
site_description: The pytest plugin for your Cookiecutter templates ğŸª
site_author: Raphael Pierzina

theme: readthedocs

repo_url: https://github.com/hackebrot/pytest-cookies

pages:
- Home: index.md
- Getting Started: getting_started.md
- Features: features.md
- About: about.md
